### ISSUE TITLE
Option to show path and url as separate options

### ISSUE THREAD

**Issue by dkniffin** [aki77/vscode-rails-routes#2]
I love this extension. It makes linking in Rails easier. However, I have on suggested improvement. When I pick a completion, it opens a secondary choice of whether I want `_path` or `_url`. 99% of the time, I want path. It would be awesome if those two versions showed up as separate suggestions in the first list, so I don't have to press enter twice. If possible, this would be great as a setting for the extension, so it could work both ways.

**Comment by aki77** [comment]
Thanks for the feedback.
I certainly think so.

I'm bothered by the fact that the order changes depending on user settings, but I'll give it a try soon!

**Comment by aki77** [comment]
I remembered.
It used to be that specification, but now it's the current specification because it increases the noise of candidate completions.
I looking for good ideas!
