### ISSUE TITLE
Allow suggestions to be used in other contexts

### ISSUE THREAD

**Issue by dkniffin** [aki77/vscode-rails-routes#3]
I recently started using [gretel](https://github.com/kzkn/gretel) for breadcrumbs. Here's an example of what the config file for that looks like:

```rb
# Root crumb
crumb :root do
  link "Home", root_path
end

# Issue list
crumb :issues do
  link "All issues", issues_path
end

# Issue
crumb :issue do |issue|
  link issue.title, issue
  parent :issues
end
```

In here, I'd like to have autocompletion for (eg) `root_path` and `issues_path`.

Digging into this library's code a bit, I think [this line](https://github.com/aki77/vscode-rails-routes/blob/master/src/RoutesCompletionProvider.ts#L15) is the one that's causing the suggestions to not show up, because my lines don't match that regex. Would it be possible to add the ability to change that regex via a config? Alternatively, you could add `link` to the list of words to match on, but that's not a generic Rails method, so I don't know if it really belongs in this library.

**Comment by aki77** [comment]
Thanks for the feedback.
I think it's a good idea to make the pattern of suggestions configurable.
If you only need it occasionally, the `railsRoutes.insert` command might be appropriate.

https://github.com/aki77/vscode-rails-routes#railsroutesinsert
